# Generated by Django 4.2.14 on 2024-08-03 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='artisan',
            old_name='user',
            new_name='profile',
        ),
    ]
